- id: '1599757764933'
  alias: Notify me if the temperature is above 6
  description: ''
  trigger:
  - above: 6
    device_id: f67b0fe0ab7d4a23b5dd24106218206b
    domain: sensor
    entity_id: sensor.temperature_7
    for:
      hours: 0
      minutes: 2
      seconds: 0
    platform: device
    type: temperature
  condition: []
  action:
  - data:
      message: Kolla dörren, det börjar bli varmt här inne.
      title: Kylskåpet
    service: notify.mobile_app_jonas_iphone
  mode: queued
  max: 2
