- id: '1599757764933'
  alias: Kylskåpstemperatur
  description: ''
  trigger:
  - above: 6
    device_id: f67b0fe0ab7d4a23b5dd24106218206b
    domain: sensor
    entity_id: sensor.temperature_7
    for:
      hours: 0
      minutes: 2
      seconds: 0
    platform: device
    type: temperature
  condition: []
  action:
  - data:
      message: Kolla dörren, det börjar bli varmt här inne.
      title: Kylskåpet
    service: notify.all_iphones
  mode: queued
  max: 2
- id: '1599763927597'
  alias: Frystemperatur
  description: ''
  trigger:
  - above: 18
    device_id: 3fb2c3258cab4d209d46c5075a5d5eac
    domain: sensor
    entity_id: sensor.temperature_4
    for:
      hours: 0
      minutes: 3
      seconds: 0
    platform: device
    type: temperature
  condition: []
  action:
  - data:
      message: Kolla dörren, det börjar bli varmt här inne.
      title: Frysen
    service: notify.all_iphones
  mode: single
- id: '1599771975814'
  alias: Dimmra upp vid pause
  description: ''
  trigger:
  - entity_id: media_player.vardagsrum_2
    from: playing
    platform: state
    to: paused
  condition:
  - condition: device
    device_id: ae3dfb97493a48f2a1207a810cca8636
    domain: light
    entity_id: light.soffbord
    type: is_on
  action:
  - brightness_pct: 50
    device_id: ae3dfb97493a48f2a1207a810cca8636
    domain: light
    entity_id: light.soffbord
    type: turn_on
  mode: single
- id: '1599772149573'
  alias: Dimmra ner vid playing
  description: ''
  trigger:
  - entity_id: media_player.vardagsrum_2
    from: paused
    platform: state
    to: playing
  condition:
  - condition: device
    device_id: ae3dfb97493a48f2a1207a810cca8636
    domain: light
    entity_id: light.soffbord
    type: is_on
  action:
  - brightness_pct: 10
    device_id: ae3dfb97493a48f2a1207a810cca8636
    domain: light
    entity_id: light.soffbord
    type: turn_on
  mode: single
- id: '1599844813109'
  alias: Homekit to device tracker
  description: ''
  trigger:
  - entity_id: input_boolean.eva_present
    platform: state
  - entity_id: input_boolean.jonas_present
    platform: state
  condition: []
  action:
  - data_template:
      dev_id: homekit_{{ trigger.to_state.name }}
      location_name: '{{ ''home'' if trigger.to_state.state == ''on'' else ''not_home''
        }}'
    service: device_tracker.see
  mode: parallel
  max: 10
