- id: '1599757764933'
  alias: Kylskåpstemperatur
  description: ''
  trigger:
  - above: 6
    device_id: f67b0fe0ab7d4a23b5dd24106218206b
    domain: sensor
    entity_id: sensor.temperature_7
    for:
      hours: 0
      minutes: 2
      seconds: 0
    platform: device
    type: temperature
  condition: []
  action:
  - data:
      message: Kolla dörren, det börjar bli varmt här inne.
      title: Kylskåpet
    service: notify.all_iphones
  mode: queued
  max: 2
- id: '1599763927597'
  alias: Frystemperatur
  description: ''
  trigger:
  - above: 18
    device_id: 3fb2c3258cab4d209d46c5075a5d5eac
    domain: sensor
    entity_id: sensor.temperature_4
    for:
      hours: 0
      minutes: 3
      seconds: 0
    platform: device
    type: temperature
  condition: []
  action:
  - data:
      message: Kolla dörren, det börjar bli varmt här inne.
      title: Frysen
    service: notify.all_iphones
  mode: single
