version: "3.3"

services:
  traefik:
    image: "traefik:v2.0.0-rc3"
    container_name: "traefik"
    command:
      #- "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.mytlschallenge.acme.tlschallenge=true"
      - "--certificatesresolvers.mytlschallenge.acme.email=jonas@brusman.se"
      - "--certificatesresolvers.mytlschallenge.acme.storage=/traefik_conf/letsencrypt/acme.json"
      - "--providers.file.filename=/traefik_conf/dynamic-conf.toml"
      - "--providers.file.watch=true"
    ports:
      - "443:443"
      - "8181:8080"
    volumes:
      - "./traefik:/traefik_conf"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    restart: always

  portainer:
    image: portainer/portainer
    restart: always
    ports:
      - "9000:9000"
    command: -H unix:///var/run/docker.sock
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.portainer.rule=Host(`portainer.brusman.se`)"
      - "traefik.http.routers.portainer.entrypoints=websecure"
      - "traefik.http.routers.portainer.tls.certresolver=mytlschallenge"
    restart: always

  unifi:
    image: jacobalberty/unifi:arm32v7
    restart: unless-stopped
    ports:
      - 8080/tcp # - Device command/control
      - 8443/tcp # - Web interface + API
      - 8843/tcp # - HTTPS portal
      - 3478/udp # - STUN service
      - 6789/tcp # - Speed Test (unifi5 only)
    environment:
      - TZ=Europe/Stockholm
    volumes:
      - /home/pi/unifi:/unifi

volumes:
  portainer_data:
