resources:
  - url: /community_plugin/mini-media-player/mini-media-player-bundle.js
    type: module
title: Home
views:
  - path: default_view
    title: Översikt
    badges:
      - entity: binary_sensor.hk_presence_jonas
      - entity: binary_sensor.hk_presence_eva
      - entity: sensor.lagenheten_temperature
      - entity: sensor.lagenheten_humidity
      - entity: sensor.yr_symbol
      - entity: sun.sun
    cards:
      - type: entities
        entities:
          - light.taklampa_2
        title: Hallen
        show_header_toggle: true
      - type: entities
        entities:
          - entity: light.koksbord
          - entity: switch.vitrinskap
          - entity: light.kok_fonster_hoger
          - entity: light.kok_fonster_vanster
        title: Kök
        show_header_toggle: true
      - type: entities
        entities:
          - entity: light.color_temperature_light_1
          - entity: light.taklampa_3
          - entity: light.vardagsrum_farglampor
          - entity: light.color_light_1
          - entity: light.color_light_1_2
          - entity: switch.golvlampa
        title: Vardagsrum
        show_header_toggle: true
      - type: entities
        entities:
          - entity: switch.byralampan_sovrum
          - entity: light.taklampa_sovrum
        title: Sovrum
        show_header_toggle: true
      - type: entities
        entities:
          - entity: light.ny_barnrum
          - entity: switch.fonster_barnrum
          - entity: switch.byralampa_barn
        title: Arvids
        show_header_toggle: true
  - path: sonos
    title: Sonos
    cards:
      - type: custom:mini-media-player
        entity: media_player.kok_2
        icon: mdi:speaker
        artwork: cover
        hide:
          volume: false
          source: true
          power: true
        speaker_group:
          platform: sonos
          show_group_count: true
          entities:
            - entity_id: media_player.kok_2
              name: Kok 
            - entity_id: media_player.vardagsrum
              name: Vardagsrum
            - entity_id: media_player.sovrum
              name: Sovrum
            - entity_id: media_player.barnrum
              name: Arvids


      - type: custom:mini-media-player
        entity: media_player.barnrum
        icon: mdi:speaker
        artwork: cover
        hide:
          volume: false
          source: true
          power: true
        speaker_group:
          platform: sonos
          show_group_count: true
          entities:
            - entity_id: media_player.kok_2
              name: Kok
            - entity_id: media_player.vardagsrum
              name: Vardagsrum
            - entity_id: media_player.sovrum
              name: Sovrum
            - entity_id: media_player.barnrum
              name: Arvids

      - type: custom:mini-media-player
        entity: media_player.vardagsrum
        icon: mdi:speaker
        artwork: cover
        hide:
          volume: false
          source: true
          power: true
        speaker_group:
          platform: sonos
          show_group_count: true
          entities:
            - entity_id: media_player.kok_2
              name: Kok
            - entity_id: media_player.vardagsrum
              name: Vardagsrum
            - entity_id: media_player.sovrum
              name: Sovrum
            - entity_id: media_player.barnrum
              name: Arvids

      - type: custom:mini-media-player
        entity: media_player.sovrum
        icon: mdi:speaker
        artwork: cover
        hide:
          volume: false
          source: true
          power: true
        speaker_group:
          platform: sonos
          show_group_count: true
          entities:
            - entity_id: media_player.kok_2
              name: Kok
            - entity_id: media_player.vardagsrum
              name: Vardagsrum
            - entity_id: media_player.sovrum
              name: Sovrum
            - entity_id: media_player.barnrum
              name: Arvids

