resources:
  - url: /community_plugin/mini-media-player/mini-media-player-bundle.js
    type: module
  - url: /community_plugin/button-card/button-card.js
    type: module
title: Brusmans radhus
views: !include_dir_list ui-lovelace/
