[http]
  [http.routers]
    [http.routers.hassio]
      entryPoints = ["websecure"]
      service = "hassio"
      rule = "Host(`home.brusman.se`)"
      [http.routers.hassio.tls]
        certResolver = "mytlschallenge"

  [http.services]
    [http.services.hassio]
      [http.services.hassio.loadBalancer]
        [[http.services.hassio.loadBalancer.servers]]
          url = "http://192.168.0.173:8123/"
